image: docker:stable

stages:
- build
- test
- release

variables:
    DEV: bigrob8181/$CI_PROJECT_NAME:dev
    #TEST: bigrob8181/$CI_PROJECT_NAME:$CI_PIPELINE_IID
    RELEASE: bigrob8181/$CI_PROJECT_NAME:$CI_COMMIT_TAG
    LATEST: bigrob8181/$CI_PROJECT_NAME:latest

before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD"

# For Production
build_prod:
    stage: build
    script:
        - docker build --pull -t $RELEASE .
        #- docker push $RELEASE
    only:
        - tags

test_prod:
    stage: test
    #before_script:
    #    - docker pull $TEST
    script:
        - docker run --name $CI_PROJECT_NAME'_test' -d $RELEASE
        - docker ps -a | awk '{print $NF}' | grep -w $CI_PROJECT_NAME'_test' | cat
    after_script:
        - docker stop $CI_PROJECT_NAME'_test' && docker rm $CI_PROJECT_NAME'_test'
    only:
        - tags

release_prod:
    stage: release
    script:
        #- docker pull $TEST
        - docker tag $RELEASE $LATEST
        - docker push bigrob8181/$CI_PROJECT_NAME
        #- curl --header 'Content-Type: application/json' --header "PRIVATE-TOKEN: $PRIVATE_TOKEN" --data '{ "name": "$CI_COMMIT_REF_NAME", "tag_name": "$CI_COMMIT_REF_NAME", "description": "Lychee-Laravel Docker Image" }' --request POST http://gitlab.landry.me/api/v4/projects/46/releases
        - pip3 install gitlab_release
        - python3 -m gitlab_release --zip "release-${CI_COMMIT_TAG}.zip" " $CI_PRIVATE_TOKEN *

    only:
        - tags


# For Development
build_dev:
    stage: build
    script:
        - docker build --pull -t $DEV .
        - docker push $DEV
    only:
        - master

test_dev:
    stage: test
    #before_script:
    #    - docker pull $TEST
    script:
        - docker run --name $CI_PROJECT_NAME'_test' -d $DEV
        - docker ps -a | awk '{print $NF}' | grep -w $CI_PROJECT_NAME'_test' | cat
    after_script:
        - docker stop $CI_PROJECT_NAME'_test' && docker rm $CI_PROJECT_NAME'_test'
    only:
        - master

release_dev:
    stage: release
    script:
        - docker push $DEV
    only:
        - master
