image: docker:stable

stages:
- build
- test
- release

variables:
    DEV: bigrob8181/$CI_PROJECT_NAME:dev
    RELEASE: bigrob8181/$CI_PROJECT_NAME:$CI_COMMIT_TAG
    LATEST: bigrob8181/$CI_PROJECT_NAME:latest

#before_script:
#    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD"

# For Production
build_prod:
    stage: build
    script:
        - docker build --pull -t $RELEASE .
    only:
        - tags

test_prod:
    stage: test
    script:
        - docker run --name $CI_PROJECT_NAME'_test' -d $RELEASE
        - docker ps -a | awk '{print $NF}' | grep -w $CI_PROJECT_NAME'_test' | cat
    after_script:
        - docker stop $CI_PROJECT_NAME'_test' && docker rm $CI_PROJECT_NAME'_test'
    only:
        - tags

release_prod:
    stage: release
    before_script:
        - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD"
    script:
        - docker tag $RELEASE $LATEST
        - docker push bigrob8181/$CI_PROJECT_NAME
    after_script:
        - apk add --no-cache python3 && \
            python3 -m ensurepip && \
            rm -r /usr/lib/python*/ensurepip && \
            pip3 install --upgrade pip setuptools && \
            if [ ! -e /usr/bin/pip ]; then ln -s pip3 /usr/bin/pip ; fi && \
            if [[ ! -e /usr/bin/python ]]; then ln -sf /usr/bin/python3 /usr/bin/python; fi && \
            rm -r /root/.cache
        - pip3 install gitlab_release
        - python3 -m gitlab_release --zip "release-${CI_COMMIT_TAG}.zip" " $CI_PRIVATE_TOKEN *

    only:
        - tags


# For Development
build_dev:
    stage: build
    script:
        - docker build --pull -t $DEV .
    only:
        - master

test_dev:
    stage: test
    script:
        - docker run --name $CI_PROJECT_NAME'_test' -d $DEV
        - docker ps -a | awk '{print $NF}' | grep -w $CI_PROJECT_NAME'_test' | cat
    after_script:
        - docker stop $CI_PROJECT_NAME'_test' && docker rm $CI_PROJECT_NAME'_test'
    only:
        - master

release_dev:
    stage: release
    before_script:
        - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD"
    script:
        - docker push $DEV
    only:
        - master
